export const PROGRAMMING_AREAS = [
    { label: "Web Development", value: "web-development" },
    { label: "Mobile Development", value: "mobile-development" },
    { label: "Data Science", value: "data-science" },
    { label: "Machine Learning", value: "machine-learning" },
    { label: "Artificial Intelligence", value: "artificial-intelligence" },
    { label: "Game Development", value: "game-development" },
    { label: "Embedded Systems", value: "embedded-systems" },
    { label: "Cloud Computing", value: "cloud-computing" },
    { label: "DevOps", value: "devops" },
    { label: "Cybersecurity", value: "cybersecurity" },
    { label: "Internet of Things (IoT)", value: "internet-of-things" },
    { label: "Blockchain", value: "blockchain" },
    { label: "Augmented Reality (AR)", value: "augmented-reality" },
    { label: "Virtual Reality (VR)", value: "virtual-reality" },
    { label: "Robotics", value: "robotics" },
    { label: "Database Management", value: "database-management" },
    { label: "Networking", value: "networking" },
    { label: "System Administration", value: "system-administration" },
    { label: "Software Testing", value: "software-testing" },
    { label: "Software Development", value: "software-development" },
    { label: "Big Data", value: "big-data" },
    { label: "Natural Language Processing (NLP)", value: "natural-language-processing" },
    { label: "Computer Vision", value: "computer-vision" },
    { label: "Bioinformatics", value: "bioinformatics" },
    { label: "Quantum Computing", value: "quantum-computing" },
    { label: "UI/UX Design", value: "ui-ux-design" },
    { label: "DevTools Development", value: "devtools-development" },
    { label: "Automation", value: "automation" },
    { label: "Software Architecture", value: "software-architecture" }
  ];